language: node_js
node_js:
      - "8"
      - "9"
      - "10"
before_script:
     - export DISPLAY=:99.0
     - sh -e /etc/init.d/xvfb start
install:
     - npm install
     - npm run build
script:
      - npm test
after_success:
      - npm run test:coverage
      - "npm install coveralls && cat ./coverage/lcov.info | coveralls"